### PR TITLE
Attempt to handle wayland better

### PR DESCRIPTION
**Pull request by Schmavery**
See https://github.com/Schmavery/reprocessing/issues/74 for more info.

Pretty much a huge hack but if someone with this problem (@zploskey ?) wants to test it out when they get a chance, feel free <3 <3

### CODE REVIEW

**Comment by zploskey** [comment]
Thanks for looking into this. Did this build for you? I get:

```
  We've found a bug for you!
  /home/zach/src/reprocessing/node_modules/Reasongl/src/native/reasongl_native.re 9:5-14
  
   7 │ try (
   8 │   if (Sys.unix && Sys.getenv("WAYLAND_DISPLAY") != "") {
   9 │     Sys.setenv("SDL_VIDEODRIVER", "wayland");
  10 │   }
  11 │ ) {
  
  The value setenv can't be found in Sys
  
  Hint: Did you mean getenv?
```

**Comment by zploskey** [comment]
`Unix.putenv` should work for this purpose.

**Comment by zploskey** [comment]
Having changed `Sys.setenv` to `Unix.putenv` and running under Gnome in Fedora 28, the example repo creates a window with no window decorations like this.

screenshot from 2018-05-18 12-34-08

Huge improvement, great success!

**Comment by Schmavery** [comment]
Shoot, I had Unix.putenv at first, but must have swapped it out for some weird reason. Thanks for testing! I'm assuming this is the same result (no window decorations etc) as when you set the SDL_VIDEODRIVER env var manually in Schmavery/reprocessing#74?

**Comment by zploskey** [comment]
Yeah, I seem to recall it never had window decorations (at least in Gnome). The reason being that Gnome currently requires client-side window decorations, whereas some other Wayland compositors do not, at least according to this: https://blog.martin-graesslin.com/blog/2018/01/server-side-decorations-and-wayland/ Anyways, that's not something I think we ought to be overly concerned about. With the change to `putenv` this should be good to go.

**Comment by Schmavery** [comment]
Ah yeah, this seems to relate to the window decorations issue on sdl2 https://bugzilla.libsdl.org/show_bug.cgi?id=2710

**Pull request merged**
